### ISSUE TITLE
p12 files?

### ISSUE THREAD

**Issue by paul-uz** [golfzaptw/action-connect-ovpn#78]
I downloaded the VPN package from Sonassi, and the `.ovpn` doesn't contain the CA, User CRT or User Key. They looks to be included via an encoded/encryped p12 file?

What can I do to use the ovpn files with your action?

**Comment by simlated** [comment]
Hi, I had the same issue. Since this is from last November maybe you solved the issue, anyway:
You can extract certificates and keys from a p12 file (if you know the password used to generate the file, that could be just empty in some cases)

```openssl pkcs12 -info -in INFILE.p12 -nodes```

https://www.ssl.com/how-to/export-certificates-private-key-from-pkcs12-file-with-openssl/

Hope that helps.
